@Url = https://localhost:7235/api
@ArticleId = b80b58ea-7b8c-4968-bfd2-2f412fa1dbe3

###

// Get all articles
GET {{Url}}/articles
Accept: application/json

###

// Create article
POST {{Url}}/articles
Accept: application/json
Content-Type: application/json

{
    "title": "test 123",
    "description": "descirption123",
    "content": "content 21322131"
}

###

// Delete article
DELETE {{Url}}/articles/{{ArticleId}}
Accept: application/json

###

// Review article
PATCH {{Url}}/articles/{{ArticleId}}/review
Accept: application/json
Content-Type: application/json

{
    "decision": 1
}

###