@Url = https://localhost:7235/api
@ArticleId = 38f77de1-3248-4ddd-8b3e-0020f2e611a1

###

// Get all articles
GET {{Url}}/articles
Accept: application/json

###

// Get article
GET {{Url}}/articles/{{ArticleId}}
Accept: application/json

###

// Create article
POST {{Url}}/articles
Accept: application/json
Content-Type: application/json

{
    "title": "test 123",
    "description": "descirption123",
    "content": "content 21322131"
}

###

// Update article
PUT {{Url}}/articles/{{ArticleId}}
Accept: application/json
Content-Type: application/json

{
    "title": "test 123 up",
    "description": "descirption123 up",
    "content": "content 21322131 up"
}

###

// Delete article
DELETE {{Url}}/articles/{{ArticleId}}
Accept: application/json

###

// Review article
PATCH {{Url}}/articles/{{ArticleId}}/review
Accept: application/json
Content-Type: application/json

{
    "decision": 1
}

###